<a href="https://colab.research.google.com/github/shinderiya803/SemanticCandidateRanking/blob/main/semantic0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files # upload zipped

uploaded = files.upload()

Saving [PUB] India_runs_data_and_ai_challenge.zip to [PUB] India_runs_data_and_ai_challenge.zip

In [2]:
import zipfile # Unzip data

zip_path = "/content/[PUB] India_runs_data_and_ai_challenge.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/data")
print("Dataset extracted successfully!")

Dataset extracted successfully!

In [3]:
import os    # See the Files

for root, dirs, files in os.walk("/content/data"):
    for file in files:
        print(os.path.join(root, file))

/content/data/[PUB] India_runs_data_and_ai_challenge/.DS_Store
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/README.docx
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/redrob_signals_doc.docx
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidate_schema.json
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_spec.docx
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/submission_metadata_template.yaml
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py
/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_candidates.json
/content/data/__MACOSX/._[PUB] India_runs_data_and_ai_challenge
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/._.DS_Store
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/._India_runs_data_and_ai_challenge
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_submission.csv
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._validate_submission.py
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._job_description.docx
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_metadata_template.yaml
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._redrob_signals_doc.docx
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidate_schema.json
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._candidates.jsonl
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._sample_candidates.json
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._README.docx
/content/data/__MACOSX/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/._submission_spec.docx

In [4]:
!pip install sentence-transformers python-docx pandas scikit-learn #Install python libraries

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.12.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.19.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 7.8 MB/s eta 0:00:00
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

In [5]:
from docx import Document # Read job description

doc = Document("/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/job_description.docx")

job_description = ""

for para in doc.paragraphs:
    job_description += para.text + "\n"

print(job_description)

Job Description: Senior AI Engineer — Founding Team
Company: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineering org from scratch. This is the kind of role where the JD changes every six months because the company changes every six months. So instead of pretending we have a fixed checklist, we're going to tell you what we actually need and what we've gotten wrong before.
If you've spent your career at Google or Meta and you want a well-scoped role with a defined ladder, this isn't it.
If you've spent your career bouncing between early-stage startups and you want to "just code" without having to think about product or recruiter workflows or eval frameworks, this also isn't it.
We need someone who is simultaneously comfortable with two things that sound contradictory:
Deep technical depth in modern ML systems — embeddings, retrieval, ranking, LLMs, fine-tuning.
Scrappy product-engineering attitude — willing to ship a working ranker in a week even if the underlying ML is "obviously suboptimal," because we need to learn from real users before we know what to actually optimize for.
These are not contradictory in real life. They feel contradictory because of how engineering culture sorted itself into "researcher" vs "shipper" archetypes. We need both modes available in the same person, and we'd rather you tilt slightly toward shipper than toward researcher.

What you'd actually be doing
The high-level mandate: own the intelligence layer of Redrob's product. That means the ranking, retrieval, and matching systems that decide what recruiters see when they search for candidates and what candidates see when they search for roles.
In practical terms, your first 90 days will probably look like:
Weeks 1-3: Audit what we currently have (it's mostly BM25 + rule-based scoring, working but not great). Identify the 3-4 highest-leverage things to fix.
Weeks 4-8: Ship a v2 ranking system that demonstrably improves recruiter-engagement metrics. This will involve embeddings, hybrid retrieval, and probably some LLM-based re-ranking, but the architecture is your call.
Weeks 9-12: Set up the evaluation infrastructure — offline benchmarks, online A/B testing, recruiter-feedback loops — so we can keep improving without flying blind.
Beyond that, you'll be driving the long-term architecture of how we do candidate-JD matching at scale, mentoring the next round of hires (we're growing the team from 4 to 12 engineers in the next year), and working closely with our recruiter-experience PM on what to build.

What we mean by "5-9 years"
This is a range, not a requirement. Some people hit "senior engineer" judgment at 4 years; some never hit it after 15. We've used 5-9 because it's roughly where people we've hired into this kind of role have landed, but we'll seriously consider candidates outside the band if other signals are strong.
That said, here are the disqualifiers we actually apply:
If you've spent your career in pure research environments (academic labs, research-only roles) without any production deployment — we will not move forward. We are explicit about this. We've tried it twice and it didn't work for either side.
If your "AI experience" consists primarily of recent (under 12 months) projects using LangChain to call OpenAI — we will probably not move forward, unless you can demonstrate substantial pre-LLM-era ML production experience. We're looking for people who understood retrieval and ranking before it became fashionable.
If you are a senior engineer who hasn't written production code in the last 18 months because you've moved into "architecture" or "tech lead" roles — we will probably not move forward. This role writes code.

The skills inventory (please read carefully)
Most JDs list 20 skills and you're supposed to have all of them. We're going to do this differently.
Things you absolutely need
Production experience with embeddings-based retrieval systems (sentence-transformers, OpenAI embeddings, BGE, E5, or similar) deployed to real users. We don't care which model — we care that you've handled embedding drift, index refresh, retrieval-quality regression in production.
Production experience with vector databases or hybrid search infrastructure — Pinecone, Weaviate, Qdrant, Milvus, OpenSearch, Elasticsearch, FAISS, or something similar. Again, the specific tech doesn't matter; the operational experience does.
Strong Python. Yes really, we care about code quality.
Hands-on experience designing evaluation frameworks for ranking systems — NDCG, MRR, MAP, offline-to-online correlation, A/B test interpretation. If you've never thought about how to evaluate a ranking system rigorously, this role will be very painful.
Things we'd like you to have but won't reject you for
LLM fine-tuning experience (LoRA, QLoRA, PEFT)
Experience with learning-to-rank models (XGBoost-based or neural)
Prior exposure to HR-tech, recruiting tech, or marketplace products
Background in distributed systems or large-scale inference optimization
Open-source contributions in the AI/ML space
Things we explicitly do NOT want
This is the section most JDs skip but we think it's the most important:
Title-chasers. If your career trajectory shows you optimizing for "Senior" → "Staff" → "Principal" titles by switching companies every 1.5 years, we're not a fit. We need someone who plans to be here for 3+ years.
Framework enthusiasts. If your GitHub is full of LangChain tutorials and your blog posts are "How I used [hot framework] to build [demo]" — that's fine but it's not what we need. We need people who think about systems, not frameworks.
People who have only worked at consulting firms (TCS, Infosys, Wipro, Accenture, Cognizant, Capgemini, etc.) in their entire career. We've had bad fit experiences in both directions. If you're currently at one of these companies but have prior product-company experience, that's fine.
People whose primary expertise is computer vision, speech, or robotics without significant NLP/IR exposure. We respect your work but you'd be re-learning fundamentals here.
People whose work has been entirely on closed-source proprietary systems for 5+ years without external validation (papers, talks, open-source). We need to see how you think, not just trust that you can think.

On location, comp, and logistics
Location: Pune/Noida-preferred but flexible. We have offices in Noida and Pune(mostly used Tue/Thu). We don't require any specific number of in-office days but we expect quarterly travel for offsites. Candidates in Hyderabad, Pune, Mumbai, Delhi NCR welcome to apply. Outside India: case-by-case, but we don't sponsor work visas.
Notice period: We'd love sub-30-day notice. We can buy out up to 30 days. 30+ day notice candidates are still in scope but the bar gets higher.

The vibe check
We genuinely believe culture-fit matters more at this stage than skills-fit. Skills are teachable; the rest mostly isn't.
We work async-first and write a lot. If you find writing painful, you'll find this role painful.
We disagree openly and decide quickly. If you find that style abrasive, you'll find this role abrasive.
We move fast and break things, with the caveat that "things" are usually our internal assumptions, not user-facing systems. If you need a stable, mature codebase to be productive, you'll find this role unstable.

How to read between the lines
The "ideal candidate" we're imagining is roughly:
6-8 years total experience, of which 4-5 are in applied ML/AI roles at product companies (not pure services).
Has shipped at least one end-to-end ranking, search, or recommendation system to real users at meaningful scale.
Has strong opinions about retrieval (hybrid vs dense), evaluation (offline vs online), and LLM integration (when to fine-tune vs prompt) — and can defend them with reference to systems they actually built.
Located in or willing to relocate to Noida or Pune.
Active on Redrob platform (or has clear signal of being in the job market) so we can actually talk to them.
We are aware this is a narrow profile. We're not expecting to find many matches in a 100K candidate pool. We're explicitly OK with that — we'd rather see 10 great matches than 1000 maybes.

Final note for the participants of the Redrob hackathon
If you're reading this in the context of the Intelligent Candidate Discovery & Ranking Challenge:
The "right answer" to this JD is not "find candidates whose skills section contains the most AI keywords." That's a trap we've explicitly built into the dataset.
The right answer involves reasoning about the gap between what the JD says and what the JD means. A Tier 5 candidate may not use the words "RAG" or "Pinecone" in their profile, but if their career history shows they built a recommendation system at a product company, they're a fit. A candidate who has all the AI keywords listed as skills but whose title is "Marketing Manager" is not a fit, no matter how perfect their skill list looks.
Your ranking system should also weigh behavioral signals — a perfect-on-paper candidate who hasn't logged in for 6 months and has a 5% recruiter response rate is, for hiring purposes, not actually available. Down-weight them appropriately.
Good luck.

In [6]:
# Load candidates Data sets
import json

candidates = []

with open("/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        candidates.append(json.loads(line))

print("Number of candidates:", len(candidates))

Number of candidates: 100000

In [7]:
#inspect the first Candidate
candidates[0]

{'candidate_id': 'CAND_0000001',
 'profile': {'anonymized_name': 'Ira Vora',
  'headline': 'Backend Engineer | SQL, Spark, Cloud',
  'summary': "Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.",
  'location': 'Toronto',
  'country': 'Canada',
  'years_of_experience': 6.9,
  'current_title': 'Backend Engineer',
  'current_company': 'Mindtree',
  'current_company_size': '10001+',
  'current_industry': 'IT Services'},
 'career_history': [{'company': 'Mindtree',
   'title': 'Backend Engineer',
   'start_date': '2024-03-08',
   'end_date': None,
   'duration_months': 27,
   'is_current': True,
   'industry': 'IT Services',
   'company_size': '10001+',
   'description': 'Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.'},
  {'company': 'Dunder Mifflin',
   'title': 'Analytics Engineer',
   'start_date': '2019-07-03',
   'end_date': '2024-01-08',
   'duration_months': 55,
   'is_current': False,
   'industry': 'Paper Products',
   'company_size': '201-500',
   'description': 'Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.'}],
 'education': [{'institution': 'Lovely Professional University',
   'degree': 'B.E.',
   'field_of_study': 'Computer Science',
   'start_year': 2017,
   'end_year': 2020,
   'grade': '8.24 CGPA',
   'tier': 'tier_3'}],
 'skills': [{'name': 'Tailwind',
   'proficiency': 'intermediate',
   'endorsements': 3,
   'duration_months': 13},
  {'name': 'NLP',
   'proficiency': 'advanced',
   'endorsements': 37,
   'duration_months': 26},
  {'name': 'Image Classification',
   'proficiency': 'advanced',
   'endorsements': 7,
   'duration_months': 40},
  {'name': 'Fine-tuning LLMs',
   'proficiency': 'advanced',
   'endorsements': 21,
   'duration_months': 36},
  {'name': 'Weights & Biases',
   'proficiency': 'intermediate',
   'endorsements': 13,
   'duration_months': 30},
  {'name': 'Speech Recognition',
   'proficiency': 'advanced',
   'endorsements': 52,
   'duration_months': 33},
  {'name': 'Photoshop',
   'proficiency': 'intermediate',
   'endorsements': 8,
   'duration_months': 24},
  {'name': 'TTS',
   'proficiency': 'advanced',
   'endorsements': 56,
   'duration_months': 60},
  {'name': 'LoRA',
   'proficiency': 'intermediate',
   'endorsements': 0,
   'duration_months': 28},
  {'name': 'Apache Beam',
   'proficiency': 'intermediate',
   'endorsements': 4,
   'duration_months': 9},
  {'name': 'AWS',
   'proficiency': 'beginner',
   'endorsements': 5,
   'duration_months': 8},
  {'name': 'Flask',
   'proficiency': 'beginner',
   'endorsements': 15,
   'duration_months': 15},
  {'name': 'BentoML',
   'proficiency': 'intermediate',
   'endorsements': 3,
   'duration_months': 36},
  {'name': 'Milvus',
   'proficiency': 'advanced',
   'endorsements': 40,
   'duration_months': 35},
  {'name': 'GANs',
   'proficiency': 'advanced',
   'endorsements': 12,
   'duration_months': 19},
  {'name': 'Statistical Modeling',
   'proficiency': 'intermediate',
   'endorsements': 9,
   'duration_months': 8},
  {'name': 'GCP',
   'proficiency': 'beginner',
   'endorsements': 7,
   'duration_months': 2}],
 'certifications': [],
 'languages': [{'language': 'English', 'proficiency': 'professional'},
  {'language': 'Hindi', 'proficiency': 'conversational'}],
 'redrob_signals': {'profile_completeness_score': 86.9,
  'signup_date': '2025-10-16',
  'last_active_date': '2026-05-20',
  'open_to_work_flag': True,
  'profile_views_received_30d': 23,
  'applications_submitted_30d': 2,
  'recruiter_response_rate': 0.34,
  'avg_response_time_hours': 177.8,
  'skill_assessment_scores': {'NLP': 38.8,
   'Image Classification': 64.8,
   'Fine-tuning LLMs': 41.6,
   'Speech Recognition': 53.7},
  'connection_count': 356,
  'endorsements_received': 35,
  'notice_period_days': 60,
  'expected_salary_range_inr_lpa': {'min': 18.7, 'max': 36.1},
  'preferred_work_mode': 'onsite',
  'willing_to_relocate': False,
  'github_activity_score': 9.2,
  'search_appearance_30d': 249,
  'saved_by_recruiters_30d': 4,
  'interview_completion_rate': 0.71,
  'offer_acceptance_rate': 0.58,
  'verified_email': True,
  'verified_phone': True,
  'linkedin_connected': False}}

In [8]:
def candidate_to_text(candidate):

    profile = candidate['profile']

    headline = profile.get('headline', '')
    summary = profile.get('summary', '')
    title = profile.get('current_title', '')
    experience = str(profile.get('years_of_experience', ''))

    skills = " ".join(
        skill['name']
        for skill in candidate['skills']
    )

    career = " ".join(
        job['description']
        for job in candidate['career_history']
    )

    text = f"""
    {headline}

    {summary}

    Current Role:
    {title}

    Experience:
    {experience} years

    Skills:
    {skills}

    Career History:
    {career}
    """

    return text

In [9]:
!pip install sentence-transformers # install Sentence transformer

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.12.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.19.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers) (1.5.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [10]:
#Load Model
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [11]:
# convert all candidates into text
candidate_texts = [candidate_to_text(candidate)for candidate in candidates]

print(candidate_texts[0])

    Backend Engineer | SQL, Spark, Cloud

    Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

    Current Role:
    Backend Engineer

    Experience:
    6.9 years

    Skills:
    Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP

    Career History:
    Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure. Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.

In [12]:
# Generate the job embedding
job_embedding = model.encode(job_description,normalize_embeddings=True)

In [13]:
#define Relevant Keyword
good_keywords = [ "retrieval","ranking","recommendation", "embedding","sentence-transformers", "faiss", "milvus","qdrant","weaviate",
                 "pinecone","elasticsearch","opensearch","llm", "fine-tuning", "lora","peft","rag","vector", "search"]

In [14]:
#create candidate document
def candidate_document(candidate):

    profile = candidate['profile']

    text = ""

    text += profile.get('headline', '') + " "
    text += profile.get('summary', '') + " "

    for job in candidate['career_history']:
        text += job.get('title', '') + " "
        text += job.get('description', '') + " "

    for skill in candidate['skills']:
        text += skill['name'] + " "

    return text.lower()

In [15]:
#filter Candidate
filtered_indices = []

for i, candidate in enumerate(candidates):

    years = candidate['profile']['years_of_experience']

    if years < 4 or years > 10:
        continue

    doc = candidate_document(candidate)

    score = sum(
        keyword in doc
        for keyword in good_keywords
    )

    if score >= 2:
        filtered_indices.append(i)

print("Filtered candidates:", len(filtered_indices))

Filtered candidates: 21760

In [16]:
#Create filter Candidate list
filtered_candidates = [
    candidates[i]
    for i in filtered_indices
]

print(len(filtered_candidates))

21760

In [17]:
# Create candidate Texts
filtered_candidate_texts = [
      candidate_to_text(candidate)
    for candidate in filtered_candidates
]

print(filtered_candidate_texts[0][:1000])

    Backend Engineer | SQL, Spark, Cloud

    Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

    Current Role:
    Backend Engineer

    Experience:
    6.9 years

    Skills:
    Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP

    Career History:
    Implemented streaming data pipel

In [18]:
# Generate Embedding
import numpy as np

filtered_embeddings = model.encode(
    filtered_candidate_texts,
    batch_size=512,
    normalize_embeddings=True,
    show_progress_bar=True
)

filtered_embeddings = np.array(filtered_embeddings)

print(filtered_embeddings.shape)

Batches:   0%|          | 0/43 [00:00<?, ?it/s]

(21760, 384)

In [19]:
# compute Semantic similarities
similarities = filtered_embeddings @ job_embedding

In [20]:
#Get Top 500 Candidates
top_k = 500

top_indices = np.argsort(similarities)[::-1][:top_k]

print(top_indices[:10])

[18457  6843 16922 10990 12950 21192 20180 13834 21467 11906]

In [21]:
# Create Top Candidate list
top_candidates = [
    filtered_candidates[i]
    for i in top_indices
]

print(len(top_candidates))

500

In [22]:
#Skill Score
core_skills = ["embedding","retrieval","ranking","llm","fine-tuning","faiss","milvus",
               "qdrant","weaviate","pinecone","python",  "lora","peft", "search"]

def skill_score(candidate):

    skills = [
        skill['name'].lower()
        for skill in candidate['skills']
    ]

    matches = sum(
        keyword in " ".join(skills)
        for keyword in core_skills
    )

    return matches / len(core_skills)

In [23]:
#Experience Score
def experience_score(candidate):

    years = candidate['profile']['years_of_experience']

    if 5 <= years <= 9:
        return 1.0

    elif 4 <= years < 5:
        return 0.8

    elif 9 < years <= 10:
        return 0.8

    else:
        return 0.4

In [24]:
#redrobe Score
def redrob_score(candidate):

    signals = candidate['redrob_signals']

    score = 0

    if signals['open_to_work_flag']:
        score += 0.2

    score += (
        signals['recruiter_response_rate']
    ) * 0.2

    score += (
        signals['interview_completion_rate']
    ) * 0.2

    score += (
        signals['offer_acceptance_rate']
    ) * 0.2

    score += (
        signals['github_activity_score'] / 100
    ) * 0.2

    return score

In [25]:
#Combine Everything
ranked_candidates = []

for idx in top_indices:

    candidate = filtered_candidates[idx]

    semantic = similarities[idx]

    skill = skill_score(candidate)

    exp = experience_score(candidate)

    redrob = redrob_score(candidate)

    final_score = (
        0.4 * semantic
        + 0.25 * skill
        + 0.15 * exp
        + 0.20 * redrob
    )

    ranked_candidates.append(
        (
            candidate['candidate_id'],
            final_score
        )
    )

In [26]:
# Sort
ranked_candidates.sort(
    key=lambda x: x[1],
    reverse=True
)

ranked_candidates[:10]

[('CAND_0063826', np.float32(0.64715195)),
 ('CAND_0001537', np.float32(0.64307886)),
 ('CAND_0052994', np.float32(0.6413647)),
 ('CAND_0016317', np.float32(0.63606286)),
 ('CAND_0077776', np.float32(0.63491493)),
 ('CAND_0039347', np.float32(0.63071865)),
 ('CAND_0013842', np.float32(0.6245987)),
 ('CAND_0017495', np.float32(0.62367344)),
 ('CAND_0092070', np.float32(0.6232235)),
 ('CAND_0074425', np.float32(0.6196697))]

In [27]:
#Career History score
good_terms = ["retrieval", "ranking","recommendation","search","embedding",
              "vector","llm","fine-tuning","rag"]

bad_terms = ["speech","tts","asr","computer vision",
             "object detection","robotics"]

def career_score(candidate):

    text = ""

    for job in candidate['career_history']:
        text += " "
        text += job['title'].lower()
        text += " "
        text += job['description'].lower()

    score = 0

    for term in good_terms:
        if term in text:
            score += 1

    for term in bad_terms:
        if term in text:
            score -= 1

    score = max(score, 0)

    return min(score / len(good_terms), 1)

In [28]:
# Consulting Companies penalties
service_companies = ["tcs","infosys","wipro","cognizant","capgemini","accenture"]

def consulting_penalty(candidate):

    companies = [
        job['company'].lower()
        for job in candidate['career_history']
    ]

    count = 0

    for company in companies:
        if any(
            service in company
            for service in service_companies
        ):
            count += 1

    if count == len(companies):
        return 0.3

    return 0

In [29]:
#Improvised Final Score
improved_ranked_candidates = []

for idx in top_indices:

    candidate = filtered_candidates[idx]

    semantic = similarities[idx]

    skill = skill_score(candidate)

    exp = experience_score(candidate)

    redrob = redrob_score(candidate)

    career = career_score(candidate)

    penalty = consulting_penalty(candidate)

    final_score = (
        0.35 * semantic
        + 0.20 * skill
        + 0.15 * exp
        + 0.15 * redrob
        + 0.15 * career
        - penalty
    )

    improved_ranked_candidates.append(
        (
            candidate['candidate_id'],
            final_score
        )
    )

In [30]:
# Sort
improved_ranked_candidates.sort(
    key=lambda x: x[1],
    reverse=True
)

improved_ranked_candidates[:20]

[('CAND_0063826', np.float32(0.5775889)),
 ('CAND_0052994', np.float32(0.57292575)),
 ('CAND_0074425', np.float32(0.5726886)),
 ('CAND_0075318', np.float32(0.5721328)),
 ('CAND_0012918', np.float32(0.5687017)),
 ('CAND_0016317', np.float32(0.5683959)),
 ('CAND_0091413', np.float32(0.5671925)),
 ('CAND_0001537', np.float32(0.55811906)),
 ('CAND_0083405', np.float32(0.55604964)),
 ('CAND_0001980', np.float32(0.5556242)),
 ('CAND_0037933', np.float32(0.55377746)),
 ('CAND_0077776', np.float32(0.5534406)),
 ('CAND_0024407', np.float32(0.5494571)),
 ('CAND_0039347', np.float32(0.5493188)),
 ('CAND_0045899', np.float32(0.5492764)),
 ('CAND_0082137', np.float32(0.54485965)),
 ('CAND_0002631', np.float32(0.5448305)),
 ('CAND_0013842', np.float32(0.54313815)),
 ('CAND_0017495', np.float32(0.5426285)),
 ('CAND_0092070', np.float32(0.54172415))]

In [31]:
improved_ranked_candidates[:10]

[('CAND_0063826', np.float32(0.5775889)),
 ('CAND_0052994', np.float32(0.57292575)),
 ('CAND_0074425', np.float32(0.5726886)),
 ('CAND_0075318', np.float32(0.5721328)),
 ('CAND_0012918', np.float32(0.5687017)),
 ('CAND_0016317', np.float32(0.5683959)),
 ('CAND_0091413', np.float32(0.5671925)),
 ('CAND_0001537', np.float32(0.55811906)),
 ('CAND_0083405', np.float32(0.55604964)),
 ('CAND_0001980', np.float32(0.5556242))]

In [32]:
#inspect sample submission
import pandas as pd

sample = pd.read_csv("/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/sample_submission.csv")

sample.head()

,candidate_id,rank,score,reasoning
0,CAND_0004989,1,0.992,HR Manager with 6.1 yrs; 9 AI core skills; res...
1,CAND_0001195,2,0.984,HR Manager with 8.7 yrs; 9 AI core skills; res...
2,CAND_0003114,3,0.976,ML Engineer with 6.4 yrs; 4 AI core skills; re...
3,CAND_0000339,4,0.968,Content Writer with 8.3 yrs; 8 AI core skills;...
4,CAND_0001082,5,0.960,HR Manager with 5.0 yrs; 8 AI core skills; res...

In [33]:
submission = pd.DataFrame(
    improved_ranked_candidates,
    columns=['candidate_id', 'score']
)

submission.to_csv(
    "submission.csv",
    index=False
)

submission.head()

   candidate_id     score
0  CAND_0063826  0.577589
1  CAND_0052994  0.572926
2  CAND_0074425  0.572689
3  CAND_0075318  0.572133
4  CAND_0012918  0.568702

In [34]:
top_100 = improved_ranked_candidates[:100]

submission_rows = []

for rank, (candidate_id, score) in enumerate(top_100, start=1):

    submission_rows.append({
        "candidate_id": candidate_id,
        "rank": rank,
        "score": float(score),
        "reasoning":
        "Strong semantic match with required AI retrieval/ranking skills, relevant experience and positive platform signals."
    })

submission = pd.DataFrame(submission_rows)

submission.to_csv(
    "submission.csv",
    index=False
)

submission.head()

,candidate_id,rank,score,reasoning
0,CAND_0063826,1,0.577589,Strong semantic match with required AI retriev...
1,CAND_0052994,2,0.572926,Strong semantic match with required AI retriev...
2,CAND_0074425,3,0.572689,Strong semantic match with required AI retriev...
3,CAND_0075318,4,0.572133,Strong semantic match with required AI retriev...
4,CAND_0012918,5,0.568702,Strong semantic match with required AI retriev...

In [35]:
submission.to_csv(
    "submission.csv",
    index=False
)

print("Submission saved successfully!")

Submission saved successfully!

In [36]:
!find /content -name "validate_submission.py"

/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py

In [37]:
!python "/content/data/[PUB] India_runs_data_and_ai_challenge/India_runs_data_and_ai_challenge/validate_submission.py" submission.csv

Submission is valid.